

#mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/frame-demo?useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout: 10000
#      idle-timeout: 30000
#      max-lifetime: 900000
#    type: com.zaxxer.hikari.HikariDataSource

  #纯粹多数据源
#  datasource:
#    dynamic:
#      primary: teacher #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        teacher:
#          url: jdbc:mysql://localhost:3306/frame-demo?useSSL=false
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            connection-test-query: SELECT 1
#            connection-timeout: 10000
#            idle-timeout: 30000
#            max-lifetime: 900000
#          type: com.zaxxer.hikari.HikariDataSource
#        student:
#          url: jdbc:mysql://192.16.28.219:3306/test?useSSL=false
#          username: root
#          password: sne4mysql
#          driver-class-name: com.mysql.jdbc.Driver
#          hikari:
#            connection-test-query: SELECT 1
#            connection-timeout: 10000
#            idle-timeout: 30000
#            max-lifetime: 900000
#          type: com.zaxxer.hikari.HikariDataSource

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#  type-aliases-package: com.ww

